---
# tasks file for reverse-proxy
 - name: install nginx
   apt: pkg=nginx state=present
   tags:
    - nginx
 - name: copy index.html file
   template: src=index.html
             dest=/var/www/html/index.html  
 - name: copying web.conf file
   template: src=web.conf 
             dest=/etc/nginx/conf.d/web.conf
 - name: copying default.conf file
   template: src=default.conf
             dest=/etc/nginx/conf.d/default.conf           
   notify:
    - restart nginx
   tags:
    - nginx
  
